version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
    open-pull-requests-limit: 1 # This avoids PR noises and is just a notification. We can bump all deps with one PR.
    versioning-strategy: increase
    labels:
      - 'pr: dependencies'
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels:
      - 'pr: dependencies'
